[package]
name = "rays"
version = "0.1.0"
authors = ["Michael Nye <thenyeguy@gmail.com>"]

[dependencies]
clap = "2.32.0"
cpuprofiler = "0.0.3"
image = "0.20.1"
indicatif = "0.9.0"
nalgebra = "0.16.8"
num = "0.2.0"
palette = "0.4.1"
rand = "0.5.5"
rayon = "1.0.3"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
