[package]
name = "rays"
version = "0.1.0"
authors = ["Michael Nye <thenyeguy@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
cpuprofiler = "0.0.3"
image = "0.20.1"
indicatif = "0.9.0"
palette = "0.4.1"
rand = "0.5.5"
rayon = "1.0.3"
regex = "1.0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
